# Generated by Django 5.0.1 on 2024-01-30 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
